package com.moutamid.justbee.utilis;

public enum Types {
    NULL,
    CHANGE_LOCATION_ALL,
    CHANGE_FEED_ALL,
    CHANGE_TREAT_ALL,
    CHANGE_LOCATION,
    CHANGE_FEED,
    CHANGE_PEST,
    CHANGE_TREAT,
    CHANGE_NEW_QUEEN,
    CHANGE_BROOD_ADD,
    CHANGE_BROOD_REMOVE,
    CHANGE_HONEY_PRODUCTION,
    CHANGE_COLONY_ADD,
    CHANGE_COLONY_REMOVE,
}
